// src/utils/theme.js
// Design system avec support multi-thème : dark / light / blue

export const themes = {

  // ── Thème sombre (défaut) ────────────────────────────────────────
  dark: {
    name: 'Sombre',
    icon: '🌙',
    bg:           '#0A0E1A',
    bgCard:       '#111827',
    bgInput:      '#1C2333',
    border:       '#1E2D45',
    accent:       '#00D4FF',
    accentDim:    '#0A3A4A',
    success:      '#00E096',
    successDim:   '#0A3B2A',
    warning:      '#FFB800',
    warningDim:   '#3A2D00',
    danger:       '#FF4757',
    dangerDim:    '#3A0A10',
    textPrimary:  '#F0F4FF',
    textSecondary:'#7A8BA8',
    textMuted:    '#3D4F6A',
    arrival:      '#00E096',
    coffeeMorn:   '#00BFFF',
    lunch:        '#FF9F43',
    coffeeAftn:   '#A29BFE',
    departure:    '#FF4757',
  },

  // ── Thème clair ──────────────────────────────────────────────────
  light: {
    name: 'Clair',
    icon: '☀️',
    bg:           '#F5F7FA',
    bgCard:       '#FFFFFF',
    bgInput:      '#EEF1F7',
    border:       '#D8DEE9',
    accent:       '#0077CC',
    accentDim:    '#DCEEFF',
    success:      '#00875A',
    successDim:   '#D4F5E9',
    warning:      '#D97706',
    warningDim:   '#FEF3C7',
    danger:       '#DC2626',
    dangerDim:    '#FEE2E2',
    textPrimary:  '#111827',
    textSecondary:'#4B5563',
    textMuted:    '#9CA3AF',
    arrival:      '#00875A',
    coffeeMorn:   '#0077CC',
    lunch:        '#D97706',
    coffeeAftn:   '#7C3AED',
    departure:    '#DC2626',
  },

  // ── Thème bleu nuit ──────────────────────────────────────────────
  navy: {
    name: 'Marine',
    icon: '🌊',
    bg:           '#0D1B2A',
    bgCard:       '#1B2E45',
    bgInput:      '#162438',
    border:       '#1E3A5F',
    accent:       '#4FC3F7',
    accentDim:    '#0A2A3A',
    success:      '#43D9AD',
    successDim:   '#0A2A22',
    warning:      '#FDD663',
    warningDim:   '#2A2200',
    danger:       '#FF6B81',
    dangerDim:    '#2A0A10',
    textPrimary:  '#E8F4FD',
    textSecondary:'#7EB8D4',
    textMuted:    '#3A6080',
    arrival:      '#43D9AD',
    coffeeMorn:   '#4FC3F7',
    lunch:        '#FDD663',
    coffeeAftn:   '#C3A6FF',
    departure:    '#FF6B81',
  },

  // ── Thème chaleureux (sépia) ─────────────────────────────────────
  warm: {
    name: 'Chaud',
    icon: '🍂',
    bg:           '#1C1510',
    bgCard:       '#2A1F17',
    bgInput:      '#231A12',
    border:       '#3D2B1F',
    accent:       '#F4A261',
    accentDim:    '#3A1F0A',
    success:      '#6FCF97',
    successDim:   '#0A2A15',
    warning:      '#F4A261',
    warningDim:   '#3A1F0A',
    danger:       '#EB5757',
    dangerDim:    '#2A0A0A',
    textPrimary:  '#F5ECD7',
    textSecondary:'#B89A7E',
    textMuted:    '#6B4F38',
    arrival:      '#6FCF97',
    coffeeMorn:   '#F4A261',
    lunch:        '#F2C94C',
    coffeeAftn:   '#BB86FC',
    departure:    '#EB5757',
  },
};

export const radius = {
  sm: 6,
  md: 12,
  lg: 16,
  xl: 24,
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};
